### PR TITLE
Update bot to use node 22

### LINKED ISSUE #2: Bot needs modernizing. It doesn't work with newer versions of node / npm
CC @vincentfretin

### PR DESCRIPTION
**Pull request by vincentfretin**
This closes #2 

Once merged, to update on the server:
```
npm uninstall -g forever
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
nvm install 22
nvm alias default 22
rm -rf node_modules/
npm install
```

### CODE REVIEW

**Comment by vincentfretin** [comment]
If by any change you have the tests/fixtures/aframeCommitComment.json file uncommited somewhere, we can bring back the tests that were using that.

**Comment by vincentfretin** [comment]
@dmarcos https://github.com/aframevr/aframe-site/pull/539 would need to be merged first and then this PR.
I removed 
```
// Limit memory usage.
childProcess.execSync('npm config set jobs 1');
```
that doesn't exist anymore. I'm not sure if that would be an issue on your current aws instance and latest npm version. I guess you should try and see if that breaks or not.

**Comment by dmarcos** [comment]
Thanks!

**Comment by dmarcos** [comment]
Merged this and server still fails to generate the builds. I upgraded to `Ubuntu 20.04.6 LTS` and node `v22.7.0`

Most strange is that I can run `npm run dist` manually and the dist generates but when running through the [bumbAframeDist script](https://github.com/supermedium/a-frobot/blob/master/lib/bumpAframeDist.js#L28) I see in the logs that `npm install` is failing silently and when the build is not produced:

```
  Error: Command failed: npm run dist
sh: 1: webpack: not found

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:421:12)
    at ChildProcess.emit (node:events:520:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'npm run dist'
}
sh: 1: webpack: not found
```

No idea what the difference is

**Comment by dmarcos** [comment]
I made sure to remove `package-lock.json` and don't see webpack in node_modules

**Comment by dmarcos** [comment]
```Current branch master is up to date.

Running npm install --only="dev"...
npm warn invalid config only="dev" set in command line options
npm warn invalid config Must be one of: null, prod, production


up to date, audited 74 packages in 5s

6 packages are looking for funding
  run `npm fund` for details

7 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

Running npm install...

up to date, audited 74 packages in 2s```

Logs of `npm install`

**Comment by dmarcos** [comment]
After running `npm install` manually I get

added 1126 packages, and audited 1200 packages in 15s

and webpack is in the node_modules directory as expected.

**Comment by dmarcos** [comment]
Different results when running commands from script (below) and manually

```
   async.series([
      execCommand('git reset --hard HEAD', 'aframe'),
      execCommand('git pull --rebase origin master', 'aframe'),
      execCommand('npm install --only="dev"', 'aframe'),
      execCommand('npm install', 'aframe'),
      execCommand('npm run dist', 'aframe'),
      execCommand('git status', 'aframe'),
      execCommand('git add -A .', 'aframe'),
      execCommand(`git commit -m "Bump aframe-master dist/ builds. (${data.compare})"`,
                  'aframe')
```

**Comment by vincentfretin** [comment]
We can remove the command `npm install --only="dev"` now. We have the warnings
```
npm warn invalid config only="dev" set in command line options
npm warn invalid config Must be one of: null, prod, production
```
so it seems to just do `npm install` twice.
In old npm, there was no support for `package-lock.json`. Now that it creates it, we should remove it so it installs the latest version each time, I think that was the previous behavior.
The changes are in #4

Creating `testdist.js` with
```js
const utils = require('./lib/utils');
const execCommand = utils.execCommand;
const async = require('async');

async.series([
      execCommand('git reset --hard HEAD', 'aframe'),
      execCommand('git pull --rebase origin master', 'aframe'),
      execCommand('rm package-lock.json', 'aframe'),
      execCommand('npm install', 'aframe'),
      execCommand('npm run dist', 'aframe')])
```
and running
`node testdist.js`

gives me 
```
Running git reset --hard HEAD...
HEAD is now at 8f47aa97 Update master CDN URL. (https://cdn.jsdelivr.net/gh/aframevr/aframe@90d90c2998c06fcc0361f15ec0b7fef87606b20c/dist/aframe-master.min.js)

Running git pull --rebase origin master...
warning: redirecting to https://github.com/aframevr/aframe.git/
From https://github.com/aframevr/aframe
 * branch              master     -> FETCH_HEAD

Already up to date.

Running rm package-lock.json...
Running npm install...

up to date, audited 1204 packages in 1s

178 packages are looking for funding
  run `npm fund` for details

37 vulnerabilities (15 moderate, 18 high, 4 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

Running npm run dist...
...
webpack 5.94.0 compiled successfully in 3141 ms
```

Do you have the same when you execute this?

**Comment by dmarcos** [comment]
I can try in a couple of hours but yesterday I tried also removing `npm install --only="dev"` manually and was getting the same result described above. Also removed package-lock.json and cleaned the npm cache

**Comment by dmarcos** [comment]
Yeah still had same issues. also tried removing the node_modules directory. Running commands by hand generate builds as expected but not through script. In a couple of hours, I’ll try to print node / npm version used by script to make sure it’s the same as by hand

**Comment by dmarcos** [comment]
I fixed the builds. The problem was that dev dependencies are not installed by default with `npm install`. In the past we had `npm install --only="dev"` for that purpose but had no effect after upgrading node because the option has been deprecated. The modern equivalent is `npm install --include=dev` that I added in `https://github.com/supermedium/a-frobot/commit/1c36871e5eabb094374cd1fb99f73a24e6dc57d6`

Now the builds are working again. I still don't understand why running `npm install` by hand installs the dev dependencies and we need `npm install --include=dev` through the script. Gotta be some env variable or something that is not available in the `childProcess.exec` context.

**Comment by vincentfretin** [comment]
Yes! I'm glad this is finally fixed.
Ah I think I understand, when run with forever, there is probably NODE_ENV=production defined somewhere
I reproduce the issue not installing devDependencies with
`NODE_ENV=production npm install`
added 75 packages, and audited 76 packages in 26s

**Comment by vincentfretin** [comment]
Yes that's it, it's just there
https://github.com/supermedium/a-frobot/blob/1c36871e5eabb094374cd1fb99f73a24e6dc57d6/package.json#L10

**Comment by dmarcos** [comment]
Do we still need NODE_ENV=production?

**Comment by vincentfretin** [comment]
Yes, it seems express disable or enable features based on that.
node_modules/express/lib/application.js:78:  var env = process.env.NODE_ENV || 'development';

**Pull request merged**
